CONFIG_ZMK_KEYBOARD_NAME="Torapa-chan"
CONFIG_ZMK_POINTING=y
CONFIG_I2C=y
CONFIG_INPUT=y
CONFIG_INPUT_AZOTEQ_IQS5XX=y
# No external DC/DC inductors; battery connected to VDD and VDDH.
CONFIG_SOC_DCDC_NRF52X=n
CONFIG_SOC_DCDC_NRF52X_HV=n
# No physical key available to wake from system off.
CONFIG_ZMK_SLEEP=n
