CONFIG_ZMK_KEYBOARD_NAME="Torapa-chan"
CONFIG_ZMK_POINTING=y
CONFIG_I2C=y
CONFIG_INPUT=y
CONFIG_INPUT_AZOTEQ_IQS5XX=y
# DCDC remains disabled by default: this board selects neither internal DCDC symbol.
# No physical key available to wake from system off.
CONFIG_ZMK_SLEEP=n
